/*
 * Copyright 2001:
 * Peter Andersson <petan117@student.liu.se>
 * Martin Hagman <marha189@student.liu.se>
 * Henrik Norin <henno776@student.liu.se>
 * Anna Stjerneby <annst566@student.liu.se>
 * Tim Terlegård <timte878@student.liu.se>
 * Johan Trygg <johtr599@student.liu.se>
 * Peter Åstrand <petas096@student.liu.se>
 *
 * This file is part of reMIND.
 *
 * reMIND is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * reMIND is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with reMIND; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
package mind.gui.dialog;

import java.util.Enumeration;
import java.util.Vector;

import mind.gui.*;
import mind.model.*;

/**
 * FlowPropertiesDialog.java
 * @author Peter Åstrand
 * @version 2001-05-18
 */
public class FlowPropertiesDialog extends javax.swing.JDialog {
    GUI c_gui;
    ID c_flowID;

    /** Creates new form FlowPropertiesDialog */
    public FlowPropertiesDialog(java.awt.Frame parent, boolean modal,
				GUI gui, ID flowID) {
        super (parent, modal);
	c_gui = gui;
	c_flowID = flowID;
        initComponents ();
        pack ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        tabbedPane = new javax.swing.JTabbedPane();
        generalPane = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idText = new javax.swing.JLabel();
        labelLabel = new javax.swing.JLabel();
        resourceLabel = new javax.swing.JLabel();
        resourceCombo = new javax.swing.JComboBox();
        labelText = new javax.swing.JTextField();
        optimizationsPane = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        getContentPane().setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        addWindowListener(new java.awt.event.WindowAdapter() {
		public void windowClosing(java.awt.event.WindowEvent evt) {
		    closeDialog(evt);
		}
	    }
			  );

        generalPane.setLayout(new java.awt.GridBagLayout());
	java.awt.GridBagConstraints gridBagConstraints2;
	generalPane.setName("");

	idLabel.setText("ID:");
	gridBagConstraints2 = new java.awt.GridBagConstraints();
	gridBagConstraints2.insets = new java.awt.Insets(5, 5, 5, 5);
	generalPane.add(idLabel, gridBagConstraints2);


	idText.setText(c_flowID.toString());
	gridBagConstraints2 = new java.awt.GridBagConstraints();
	gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
	gridBagConstraints2.insets = new java.awt.Insets(5, 5, 5, 5);
	generalPane.add(idText, gridBagConstraints2);


	labelLabel.setText("Label:");
	gridBagConstraints2 = new java.awt.GridBagConstraints();
	gridBagConstraints2.gridx = 0;
	gridBagConstraints2.gridy = 1;
	gridBagConstraints2.insets = new java.awt.Insets(5, 5, 5, 5);
	generalPane.add(labelLabel, gridBagConstraints2);


	resourceLabel.setText("Resource:");
	gridBagConstraints2 = new java.awt.GridBagConstraints();
	gridBagConstraints2.gridx = 0;
	gridBagConstraints2.gridy = 2;
	gridBagConstraints2.insets = new java.awt.Insets(5, 5, 5, 5);
	generalPane.add(resourceLabel, gridBagConstraints2);


	resourceCombo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    resourceComboActionPerformed(evt);
                }
            }
					);

	Vector resources = c_gui.getResources();

	for (int i = 0; i < resources.size(); i++) {
	    resourceCombo.addItem(resources.get(i));
	}

	Resource flowResource = c_gui.getResource(c_flowID);



	if (flowResource != null)
	    resourceCombo.setSelectedIndex(resources.indexOf(flowResource));

	gridBagConstraints2 = new java.awt.GridBagConstraints();
	gridBagConstraints2.gridx = 1;
	gridBagConstraints2.gridy = 2;
	gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
	gridBagConstraints2.insets = new java.awt.Insets(5, 5, 5, 5);
	generalPane.add(resourceCombo, gridBagConstraints2);

	labelText.setText(c_gui.getLabel(c_flowID));

	gridBagConstraints2 = new java.awt.GridBagConstraints();
	gridBagConstraints2.gridx = 1;
	gridBagConstraints2.gridy = 1;
	gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
	generalPane.add(labelText, gridBagConstraints2);

	tabbedPane.addTab("General", generalPane);


        tabbedPane.addTab("Optimizations", optimizationsPane);


        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = 2;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        getContentPane().add(tabbedPane, gridBagConstraints1);


        okButton.setText("OK");
	getRootPane().setDefaultButton(okButton);
        okButton.addActionListener(new java.awt.event.ActionListener() {
		public void actionPerformed(java.awt.event.ActionEvent evt) {
		    okButtonActionPerformed(evt);
		}
	    }
				   );

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.insets = new java.awt.Insets(10, 10, 10, 10);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints1.weightx = 1.0;
        getContentPane().add(okButton, gridBagConstraints1);


        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
		public void actionPerformed(java.awt.event.ActionEvent evt) {
		    cancelButtonActionPerformed(evt);
		}
	    }
				       );

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.insets = new java.awt.Insets(10, 10, 10, 10);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints1.weightx = 1.0;
        getContentPane().add(cancelButton, gridBagConstraints1);

    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
	setVisible (false);
	dispose ();
    }

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
	// Set flowlabel.
        c_gui.setFlowLabel(c_flowID, labelText.getText());

	// Set active resource if there is any
	Resource resource = ((Resource) resourceCombo.getSelectedItem());
	if (resource != null)
	    c_gui.setResource(c_flowID, resource.getID());

	setVisible(false);
	dispose();
    }

    private void resourceComboActionPerformed(java.awt.event.ActionEvent evt) {
	// Add your handling code here:
    }

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {
        setVisible (false);
        dispose ();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPanel generalPane;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idText;
    private javax.swing.JLabel labelLabel;
    private javax.swing.JLabel resourceLabel;
    private javax.swing.JComboBox resourceCombo;
    private javax.swing.JTextField labelText;
    private javax.swing.JPanel optimizationsPane;
    private javax.swing.JButton okButton;
    private javax.swing.JButton cancelButton;
    // End of variables declaration//GEN-END:variables

}
